env:
  browser: true
  es6: true
  amd: true
  node: true
extends: airbnb-base
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
    modules: true
  sourceType: module
plugins:
  - react
rules:
  comma-dangle: off
  consistent-return: off
  func-names: off
  no-console: off
  no-constant-condition: off
  no-empty: off
  no-param-reassign: off
  no-shadow: off
  no-throw-literal: off
  no-underscore-dangle: off
  no-use-before-define:
    - error
    - functions: false
  prefer-arrow-callback: off
  react/jsx-key: 1
  react/jsx-uses-react: 1
  react/jsx-uses-vars: 1
  react/jsx-wrap-multilines: 1
  react/prefer-es6-class: 1
  react/react-in-jsx-scope: 1

